version: 2

models:
  - name: fct_messages
    columns:
      - name: message_id
        tests:
          - unique
          - not_null

      - name: channel_name
        tests:
          - not_null

      - name: message_date
        tests:
          - not_null
